# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
# Prettier configuration
# https://prettier.io/docs/en/configuration.html

trailingComma: none
printWidth: 120
proseWrap: always
endOfLine: lf
overrides:
  - files: |
      "*.yaml"
      "*.yml"
    options:
      proseWrap: never
      objectWrap: collapse
  - files: |
      "*/**/*.mdc"
    options:
      parser: markdown
