# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
# Prettier configuration
# https://prettier.io/docs/en/configuration.html

trailingComma: es5
printWidth: 120
proseWrap: always
endOfLine: lf
semi: false
singleQuote: true
